### ISSUE TITLE
Quit account on dashboard，the container is still running.

### ISSUE THREAD

**Issue by 815325223** [openanalytics/shinyproxy-config-examples#11]
Hello, author，

Will the container status exit when I quit my account? The result of the current test is that the container does not end automatically. Is this normal? This is very resource intensive

**Comment by tverbeke** [comment]
Hello,

When you sign out, the container will be shut down. When you close the browser tab, the heartbeat mechanism will make sure the container is shut down (after a configurable time). Questions regarding usage can always be posted on https://support.openanalytics.eu/

Best,
Tobias
