### ISSUE TITLE
Example for setting up Influxdb

### ISSUE THREAD

**Issue by fmmattioni** [openanalytics/shinyproxy-config-examples#12]
Would you guys consider adding an example for setting up Influxdb + Kapacitor + Telegraf + Chronograf in the server?

I have a ubuntu server built in a digital ocean droplet that is running with nginx, and although I can install all the aforementioned packages, I still can't quite get it to work. All of these is still super confusing for me, so I was wondering if you guys would have a fully working example to add here? Or if you could point me to another webpage that has such example?

**Comment by LEDfan** [comment]
Hi @fmmattioni 
Since the time you opened this issue, we have worked on a new monitoring stack for ShinyProxy: https://github.com/openanalytics/shinyproxy-monitoring

This is based on Prometheus and Grafana and should be easier to get working.
