### ISSUE TITLE
Failed to create container

### ISSUE THREAD

**Issue by dtenenba** [openanalytics/shinyproxy-config-examples#2]
(Related to #1 but different)

I a am trying to run the `02-containerized-docker-engine` example and getting the following error when I click on either of the shiny apps:

```
Error
Status code: 500

Message: Failed to create container
```

*Update*: Figured out that this is because I did not pull `openanalytics/shinyproxy-demo` first. Doing that makes it work. Might want to add that to the documentation?

Thanks!

**Comment by tverbeke** [comment]
Thanks for the feedback, @dtenenba ! I added a note to the `README.md`.
