### ISSUE TITLE
Shinyapps not working on shinyproxy2.4.3 and with openjdk:11-jre

### ISSUE THREAD

**Issue by aupadh12** [openanalytics/shinyproxy-config-examples#24]
Hi Team,

We have deployed few shinyapps using shinyproxy 2.3.1 and openjdk:8-jre and they are running perfectly fine.
However, when we try to upgrade the shinyproxy to the latest available version, i.e., shinyproxy-2.4.3.jar and openjdk:11-jre, the apps do not work.
Can you please let me know if there are any significant changes between the 2 versions and what would be the best place to look at to make the shinyapps compatible?

Regards,
Ashutosh Upadhyay

**Comment by tverbeke** [comment]
Hi @aupadh12, Good to hear ShinyProxy 2.3.1 works fine for you. Can you be a bit more specific as to what does not work? A couple of configuration options have been changed (see detail in the release notes https://shinyproxy.io/downloads/), but many other deployments worked fine after upgrading to ShinyProxy 2.4.3.

**Comment by aupadh12** [comment]
Hi @tverbeke , It seems when I am switching to the newer version of shinyproxy, the overall application breaks and liveness and readiness probe fail.
Due to this the shinyapps which are called from shinyproxy pod does not work.
Do I need to change anything else in my configuration other than using useForwardHeaders?

**Comment by tverbeke** [comment]
Hi @aupadh12,

This is the shinyproxy-config-examples repo and not the shinyproxy repo. Also this seems unrelated to your original question. Closing for now.

Best,
Tobias
