### ISSUE TITLE
Shiny Proxy - LDAP authentication - allow users to stay login for 8 hours

### ISSUE THREAD

**Issue by jino-mariath** [openanalytics/shinyproxy-config-examples#28]
Hello Team,

Could you let me know do we have an option to extent LDAP / AD authentication users' login to be live till 8 hrs? 
As per the current (default) setting after-hours, the login session expired, and need to login back again. 
Users are complaining that they required more time to keep live session on Shiny Proxy. 

Could you advise? 

When I look at the documentation I do see on a session called "container-wait-time" will that help to keep the user session live for more time? 

Thank you,
Jino.

**Comment by LEDfan** [comment]
Hi

The `container-wait-time` option specifies the time ShinyProxy waits for a container to startup.
You are looking for the session timeout option, see our documentation: https://shinyproxy.io/documentation/configuration/#long-sessions

**Comment by jino-mariath** [comment]
Excellent. Thank you so much. This works well.
