### ISSUE TITLE
permission error and solution for "07-containerized-docker-swarm"

### ISSUE THREAD

**Issue by ivokwee** [openanalytics/shinyproxy-config-examples#36]
Script does not work as such. Some permission errors in docker. 

`java.io.IOException: Permission denied`

`Could not attach to network sp-example-net: rpc error: code = PermissionDenied desc = network sp-example-net not manually attachable`

Solution was to add:

1) add --attachable to when creating network:
`docker network create -d overlay --attachable sp-example-net`

2) add group when launching docker:
docker service create ...  --group $(getent group docker | cut -d: -f3)`  shinyproxy-example

I will make a PR on this.

**Comment by LEDfan** [comment]
Thanks, PR was merged!
