### ISSUE TITLE
Regarding ECS backend configuration issue

### ISSUE THREAD

**Issue by sound118** [openanalytics/shinyproxy-config-examples#43]
Hi,

Thanks for the recent upgrade of shinyproxy we could now use AWS ECS as backend to run shinyproxy. While we are configuring ShinyProxy with ECS as backend. We experienced following issues:

![image](https://github.com/openanalytics/shinyproxy-config-examples/assets/38205878/78d16709-8fed-45ed-ba40-a65dadcb473c)

![image](https://github.com/openanalytics/shinyproxy-config-examples/assets/38205878/13134c72-62a6-4d40-a53d-2529ace0fcc3)

The applicaiton.yml file is as below:
proxy:
  title: Open Analytics Shiny Proxy
  logo-url: https://www.openanalytics.eu/shinyproxy/logo.png
  authentication: simple
  containerBackend: ecs

  ecs:
    name: ${CLUSTER_NAME}
    region: ${AWS_REGION}
    subnets:
      - ${SUBNET_0}
      - ${SUBNET_1}
    security-groups: ${SECURITY_GROUP}

  users:
    - name: jack
      password: password
      groups: mathematicians
  specs:
    - id: data_dictionary
      display-name: demo_app
      description: Application demo
      container-cmd: [ "R", "-e", "shinyproxy::run_demo_app()" ]
      container-image: :**********.dkr.ecr.ap-southeast-1.amazonaws.com/demo_app:latest
      access-groups: [ scientists, mathematicians ]
      container-cpu-request: 1024
      container-memory-request: 2048
      ecs-execution-role: arn:aws:iam:::**********:role/shinyproxy-vf-ecs-ter-qa
      ecs-task-role: arn:aws:iam::**********:role/shinyproxy-vf-ecs-ter-qa

Can someone please help with this configuration issue?

**Comment by LEDfan** [comment]
Hi, the example was using an incorrect docker image, this has been fixed now.

>  2024-06-28T14:54:56.083Z WARN 1 --- [ProxyService-16] e.o.c.backend.ecs.EcsBackend : [user=jack proxyId=c6d684c9-cf19-4296-a379-781e1a2e8771 specId=data_dictionary] Not adding ECS tag "openanalytics.eu/sp-http-headers" because it is contains invalid characters (only a-zA-Z0-9 +-=._:/@ allowed)

This log message does not cause an issue, you can ignore it.

The main issue here is that ShinyProxy cannot reach your app. This could have multiple causes:

 - your app is not starting correctly -> check the task in ECS while it's starting for any error, maybe try using our shiny demo app (openanalytics/shinyproxy-demo)
 - the security groups are incorrectly configured and network access to the app is blocked -> use the setup provided in the example

I see that you are using a different IP range than in our example, this should of course work, but please make sure that all your changes to the example are correct.

**Comment by sound118** [comment]
Thanks for the response. We have checked on our side that the network has no issue as the health check has passed as shown in below screenshot.
![image](https://github.com/openanalytics/shinyproxy-config-examples/assets/38205878/7b944528-22d5-47f6-a810-110680815c1d)
 As you mentioned the docker image has been fixed now, but I don't see any image name change in this github config example for ECS. Just want to check with you the docker image in this link https://hub.docker.com/r/openanalytics/shinyproxy-snapshot/tags, 

![image](https://github.com/openanalytics/shinyproxy-config-examples/assets/38205878/ce36a58b-3b25-463f-97e2-c538225c4d8d)
I actually tried the one with the latest image tag, but still got the same error message as before, which image should I use for the correct ECS set up?

**Comment by sound118** [comment]
Another issue I am facing is, when I use simple authentication to test, after successful login, there's no application shown in the webpage, the url becomes "https://internal-shinyproxy-vf-qa-alb-1044217459.ap-southeast-1.elb.amazonaws.com/auth-success", but if I delete "auth-success" at the end of url, it shows the application in the web page, click into the app will result the error shown before , (e.g. container unresonsive...)

**Comment by sound118** [comment]
@LEDfan Hi, my latest finding is I am able to access my own R shiny application with docker image stored in ECR as shown in below cloudwatch log:
![image](https://github.com/openanalytics/shinyproxy-config-examples/assets/38205878/f50aa8d2-ffef-4809-9d83-ec694e9eab87)
The problem is the application UI won't show up, the web browser keeps showing below stuff:
![image](https://github.com/openanalytics/shinyproxy-config-examples/assets/38205878/32a51b2e-c5fe-47dd-88ab-a5091d684922)
Could you suggest what the cause was for this matter?

**Comment by LEDfan** [comment]
Please use the image `openanalytics/shinyproxy:3.1.1`. 

Regarding the network connectivity: the screenshot you posted is about the ShinyProxy container itself. The problem you are facing is between ShinyProxy and the app container. Can you post a screenshot of the security groups the app is using and the security group of ShinyProxy?

**Comment by sound118** [comment]
Below is the security group for the app itself with the source security group ID from shinyproxy
![image](https://github.com/openanalytics/shinyproxy-config-examples/assets/38205878/4cad7ab1-45fb-438a-8ce0-4bd079582191)
Below is the security group for shinyproxy 
![image](https://github.com/openanalytics/shinyproxy-config-examples/assets/38205878/7cdc8b0f-ef0a-42de-abf0-b3f760dd70ff)
Many thanks for your support!

**Comment by LEDfan** [comment]
The loadbalancer is working fine, otherwise you would not be able to reach the ShinyProxy UI. Also as mentioned above, it's expected that the UI keeps loading, since ShinyProxy is unable to reach your application.

Can you post which security groups are attached to the ShinyProxy container and which security groups are attached to the container created by ShinyProxy?

**Comment by sound118** [comment]
The security group ID sg-0c4518dc8c979592f with security group name vf-shinyproxy-test-lb-sg-qa is attached to ShinyProxy container.
The security group ID sg-05e040ad31bf70028 with security group name vf-shinyproxy-test-fg-sg-qa is attached to the container created by ShinyProxy.

**Comment by sound118** [comment]
> The loadbalancer is working fine, otherwise you would not be able to reach the ShinyProxy UI. Also as mentioned above, it's expected that the UI keeps loading, since ShinyProxy is unable to reach your application.
> 
> Can you post which security groups are attached to the ShinyProxy container and which security groups are attached to the container created by ShinyProxy?

You mentioned ShinyProxy cannot reach the application, why is there such log showing the shiny application is launched listening to port 3838
![image](https://github.com/openanalytics/shinyproxy-config-examples/assets/38205878/b8913a5d-3173-4d69-b943-5297698199f4)

**Comment by sound118** [comment]
> The loadbalancer is working fine, otherwise you would not be able to reach the ShinyProxy UI. Also as mentioned above, it's expected that the UI keeps loading, since ShinyProxy is unable to reach your application.
> 
> Can you post which security groups are attached to the ShinyProxy container and which security groups are attached to the container created by ShinyProxy?

Thanks for the hint, we have figured out the issue by updating our security group to have wider access and pointing the right security group to shinyproxy. Then we could enter our own application.

As of now, we are using simple authentication for testing purpose. With this simple authentication, after log into shinyproxy, the url goes like below screenshot with no app link on the page:
![image](https://github.com/openanalytics/shinyproxy-config-examples/assets/38205878/b4d2a782-9f57-4ac4-b14b-40f83cf6668b)
after delete "auth-success" at the end of url and hit "enter" key, it can enter the app page like below:
![image](https://github.com/openanalytics/shinyproxy-config-examples/assets/38205878/ae88f949-257b-4f7f-a394-644556ea7011)
From my previous experience with containerized shinyproxy config using version 2.6, it can automatically enter app page immediately after user login, not sure what caused this issue using ECS as backend using shinyproxy 3.1.1

**Comment by sound118** [comment]
Above issue has been resolve by referencing https://shinyproxy.io/documentation/security/#https-ssl--tls
