### ISSUE TITLE
Logging settings require specifying 'name'

### ISSUE THREAD

**Issue by DzimitryM** [openanalytics/shinyproxy-config-examples#44]
In all examples, the settings for logging in `application.yml` need to include the key `name` explicitly (`shiny.proxy.logging.file.name`).
Without the key, the log file is not created in the specified location.

```
logging:
  file:
    name: shinyproxy.log
```

**Comment by LEDfan** [comment]
Hi, thanks a lot for reporting this. I just fixed it!
