### ISSUE TITLE
Update to 2.0.1

### ISSUE THREAD

**Issue by dmenne** [openanalytics/shinyproxy-config-examples#5]
Suggestion: Please update to current version

**Comment by tverbeke** [comment]
Hi @dmenne Anything specific you would want to see updated? As far as I can see the examples have been updated for the new configuration in 2.0.0, but there is no change required going from 2.0.0 to 2.0.1. We can always have overlooked things, of course.

**Comment by dmenne** [comment]
Sorry for being diffuse:
In

https://github.com/openanalytics/shinyproxy-config-examples/blob/master/02-containerized-docker-engine/Dockerfile

it is still 1.1. I forgot to look at it when I tried, and was surprised things did not work

**Comment by tverbeke** [comment]
Fixed - thanks for the feedback!
