### ISSUE TITLE
add login.html template to templates

### ISSUE THREAD

**Issue by romunov** [openanalytics/shinyproxy-config-examples#6]
As noted [here](https://github.com/openanalytics/shinyproxy/issues/101), would you consider adding the `login.html` to  	04-custom-html-template folder?

**Comment by XiaoruiZhu** [comment]
I agree, giving the flexibility to modify login.html will be nice feature. 

BTW, could you guys illustrate the example 8: 08-api-oauth2, the README file seems not very clear. Especially the step 2, 3, and 6.

**Comment by LEDfan** [comment]
Hi, the `login.html` has been included now.
