### ISSUE TITLE
Documentation issue: first step is last

### ISSUE THREAD

**Issue by CerebralMastication** [openanalytics/shinyproxy-config-examples#9]
Hey great project!! I've got it up and running after two days of fiddling. I'm sure it's not conscious, but you're literally put the first step of the set up as the *very last line of the documentation*... this is surprising, to say the least. And resulted in it taking me two different sessions before I figured out what was up. 

I wanted everything in a container so I forked your example repo, went to section `02` and followed the instructions. It failed with a cryptic message. Lots of googling and coming back. Finally I happened to see there was more info and the very last line of the documentation should have been run first. Ok, so that's "step 1" and should be first. 

This bit:

> ShinyProxy expects relevant Docker images to be already available on the host. Before running this example, pull the Docker image used in this example with:
> 
> `sudo docker pull openanalytics/shinyproxy-demo`

So I found that confusing but now that I have it working, I think it's a wonderful project! Thank you so much for making it available.

**Comment by tverbeke** [comment]
Many thanks for the suggestion, @CerebralMastication ! We made the requirement more prominent in the README.md file (d7120822742f898834d785a68cbac12b245d1600).
